FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/vernon-cms ./cmd/api

FROM gcr.io/distroless/static-debian12

COPY --from=builder /bin/vernon-cms /bin/vernon-cms
COPY --from=builder /app/migrations /migrations

EXPOSE 8080

ENTRYPOINT ["/bin/vernon-cms"]
